### ISSUE TITLE
"Suggestions"

### ISSUE THREAD

**Issue by ile** [EvidentSolutions/raudikko#10]
Yksi, mikä olisi hyödyllinen ja ehkä helppo toteuttaa, olisi ehdotukset sanan oikeinkirjoitukseksi:

```java
Voikko voikko = new Voikko("fi");
List<String> suggestions = voikko.suggest("kasssa"); // suggestions[kassa, kassas, kassaa, kasassa]
```

**Comment by komu** [comment]
Moi,

Tuostahan on suggestions-haarassa itse asiassa jo alustava toteutus: https://github.com/EvidentSolutions/raudikko/commit/24a78838482964308200f7f00fd54c3183d762ed

Jos sinulla on tarve tälle toiminnallisuudelle, niin koita ihmeessä tuota ja anna palautetta. Voisi sitten tarvittaessa vielä korjailla tuota tai mergetä sellaisenaan tuon mukaan ja tehdä releasen. Muistaakseni suomi.fi käytti tuotakin, pitääpä kysellä niiltäkin.

**Comment by komu** [comment]
Mahdollisen keskustelun voisi siirtää PR #7:n piiriin.
