### ISSUE TITLE
Kieliopin tarkistus

### ISSUE THREAD

**Issue by ile** [EvidentSolutions/raudikko#9]
Moi,

Olisiko helppo homma lisätä kieliopin tarkistus Raudikkoon? En ainakaan heti huomannut sitä - löysin ainoastaan funktion, joka kelpuutti yhden sanan, ei kokonaisia lauseita/kappaleita.

Libvoikon java-api sisältää [tämän](https://github.com/voikko/corevoikko/blob/master/libvoikko/java/src/main/java/org/puimula/libvoikko/Voikko.java#L222):

```java
    /**
     * Check the given text for grammar errors and return a
     * list of GrammarError objects representing the errors that were found.
     * Unlike the C based API this method accepts multiple paragraphs
     * separated by newline characters.
     * @param text
     * @param language language in which error descriptions should be returned
     * @return list of grammar errors
     */
    public synchronized List<GrammarError> grammarErrors(String text, String language) {
        requireValidHandle();
        List<GrammarError> errorList = new ArrayList<GrammarError>();
        if (!isValidInput(text)) {
            return errorList;
        }
        int offset = 0;
        for (String paragraph : text.replace("\r", "\n").split("\\n")) {
            appendErrorsFromParagraph(errorList, paragraph, offset, language);
            offset += paragraph.length() + 1;
        }
        return errorList;
    }
```

**Comment by komu** [comment]
Siitä on aikaa kun luin Voikon koodia, mutta muistikuvani on se, että Voikon kieliopin tarkistus oli melko erillinen kokonaisuus joka ei perustunut samaan morfologia-virtuaalikoneeseen, jonka toteutin Raudikkoon. Eli käytännössä pitäisi käydä kaikki toi koodi läpi ja portata se Javaksi.

En usko että ainakaan minä lähden tuota toteuttamaan, koska omat tarpeeni koskevat lähinnä sanojen muuttamista perusmuotoon, jotta saadaan parempia indeksejä hakukoneelle.

**Comment by ile** [comment]
Testasin Voikon kieliopin tarkistusta, enkä saanut kovin paljon tuloksia. Eiköhän pelkkä oikoluku riitä. 

Kiitos vastauksista!
